-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 15:23:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `AlekseevStanislavDB` DEFAULT CHARACTER SET utf8 ;
USE `AlekseevStanislavDB` ;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Workers` (
  `Passport` INT NOT NULL,
  `First Name` VARCHAR(45) NULL,
  `Last Name` VARCHAR(45) NULL,
  `Fathers Name` VARCHAR(45) NULL,
  `Science degree` VARCHAR(45) NULL,
  PRIMARY KEY (`Passport`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Patients` (
  `idPatients` INT NOT NULL,
  `First Name` VARCHAR(45) NULL,
  `Last Name` VARCHAR(45) NULL,
  `Fathers Name` VARCHAR(45) NULL,
  `Passport Series` INT NULL,
  `Passport Number` INT NULL,
  `Adress` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatients`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Specialisations` (
  `idSpecializations` INT NOT NULL,
  `SpName` VARCHAR(45) NULL,
  PRIMARY KEY (`idSpecializations`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`ConsultingRooms` (
  `idCab` INT NOT NULL,
  `NUMcab` INT NULL,
  `StartWork` TIME NULL,
  `EndWork` TIME NULL,
  PRIMARY KEY (`idCab`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`Specialists` (
  `PassportSP` INT NOT NULL,
  `idSpecializationsSP` INT NOT NULL,
  `idCabSP` INT NOT NULL,
  `idSpecialist` INT NOT NULL,
  INDEX `fk_Specialists_Workers_idx` (`PassportSP` ASC) VISIBLE,
  INDEX `fk_Specialists_Specialisations1_idx` (`idSpecializationsSP` ASC) VISIBLE,
  INDEX `fk_Specialists_ConsultingRooms1_idx` (`idCabSP` ASC) VISIBLE,
  PRIMARY KEY (`idSpecialist`),
  CONSTRAINT `fk_Specialists_Workers`
    FOREIGN KEY (`PassportSP`)
    REFERENCES `AlekseevStanislavDB`.`Workers` (`Passport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialists_Specialisations1`
    FOREIGN KEY (`idSpecializationsSP`)
    REFERENCES `AlekseevStanislavDB`.`Specialisations` (`idSpecializations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialists_ConsultingRooms1`
    FOREIGN KEY (`idCabSP`)
    REFERENCES `AlekseevStanislavDB`.`ConsultingRooms` (`idCab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`PatientsCard` (
  `idPatientsPC` INT NOT NULL,
  INDEX `fk_PatientsCard_Patients1_idx` (`idPatientsPC` ASC) VISIBLE,
  CONSTRAINT `fk_PatientsCard_Patients1`
    FOREIGN KEY (`idPatientsPC`)
    REFERENCES `AlekseevStanislavDB`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `AlekseevStanislavDB`.`SEANSI` (
  `Specialists_idSpecialist` INT NOT NULL,
  INDEX `fk_SEANSI_Specialists1_idx` (`Specialists_idSpecialist` ASC) VISIBLE,
  CONSTRAINT `fk_SEANSI_Specialists1`
    FOREIGN KEY (`Specialists_idSpecialist`)
    REFERENCES `AlekseevStanislavDB`.`Specialists` (`idSpecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;